### ISSUE TITLE
error on relational-db-relation-broken

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/kfp-operators#222]
I removed kfp-api application from bundle and kfp went into error state

eg
```
juju remove-application kfp-api
```

```
2023-06-20T10:02:41.398Z [container-agent] 2023-06-20 10:02:41 DEBUG juju-log relational-db:18: Operator Framework 2.3.0 up and running.
2023-06-20T10:02:41.420Z [container-agent] 2023-06-20 10:02:41 DEBUG juju-log relational-db:18: Emitting Juju event relational_db_relation_broken.
 Error in sys.excepthook:
 Traceback (most recent call last):
   File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
     self.emit(record)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/log.py", line 41, in emit
     self.model_backend.juju_log(record.levelname, self.format(record))
   File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
     return fmt.format(record)
   File "/usr/lib/python3.8/logging/__init__.py", line 676, in format
     record.exc_text = self.formatException(record.exc_info)
   File "/usr/lib/python3.8/logging/__init__.py", line 626, in formatException
     traceback.print_exception(ei[0], ei[1], tb, None, sio)
   File "/usr/lib/python3.8/traceback.py", line 103, in print_exception
     for line in TracebackException(
   File "/usr/lib/python3.8/traceback.py", line 612, in format
     yield from self.__context__.format(chain=chain)
   File "/usr/lib/python3.8/traceback.py", line 617, in format
     yield from self.format_exception_only()
   File "/usr/lib/python3.8/traceback.py", line 566, in format_exception_only
     stype = smod + '.' + stype
 TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
 
 Original exception was:
 Traceback (most recent call last):
   File "./src/charm.py", line 517, in _get_db_data
     db_data = self._get_mysql_data()
   File "./src/charm.py", line 446, in _get_mysql_data
     relation = self._get_db_relation("mysql")
   File "./src/charm.py", line 436, in _get_db_relation
     raise GenericCharmRuntimeError(
 <unknown>GenericCharmRuntimeError: Database relation mysql is not established or empty
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "./src/charm.py", line 683, in <module>
     main(KfpApiOperator)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/main.py", line 441, in main
     _emit_charm_event(charm, dispatcher.event_name)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
     event_to_emit.emit(*args, **kwargs)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/framework.py", line 354, in emit
     framework._emit(event)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/framework.py", line 830, in _emit
     self._reemit(event_path)
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/framework.py", line 919, in _reemit
     custom_handler(event)
   File "./src/charm.py", line 662, in _on_relational_db_relation_remove
     self._on_event(event)
   File "./src/charm.py", line 669, in _on_event
     config_json = self._generate_config(interfaces)
   File "./src/charm.py", line 217, in _generate_config
     db_data = self._get_db_data()
   File "./src/charm.py", line 524, in _get_db_data
     db_data = self._get_relational_db_data()
   File "./src/charm.py", line 482, in _get_relational_db_data
     relation_data = self.database.fetch_relation_data()
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 508, in fetch_relation_data
     key: value for key, value in relation.data[relation.app].items() if key != "data"
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/venv/ops/model.py", line 1346, in __getitem__
     raise KeyError(
 KeyError: 'Cannot index relation data with "None". Are you trying to access remote app data during a relation-broken event? This is not allowed.'

```

**Comment by ca-scribner** [comment]
@dnplas mentioned in a call that this may be happening because:
* on remove, we render our kubeflow manifests to know what we need to delete
* rendering kubeflow manifests requires some relation data, which is unavailable

Because of these things, we hit errors during remove.  

A fix for this is the newly added [`KRH.delete()`](https://github.com/canonical/charmed-kubeflow-chisme/blob/2b65da2e8acc0ac6c10eee3f3d4dc42973d4cdb2/src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py#L144).  It deletes using a different approach (using labels rather than re-rendering manifests) and can likely solve this issue.

**Comment by beliaev-maksim** [comment]
@ca-scribner 

looking in the trace I doubt

```
   File "./src/charm.py", line 524, in _get_db_data
     db_data = self._get_relational_db_data()
   File "./src/charm.py", line 482, in _get_relational_db_data
     relation_data = self.database.fetch_relation_data()
   File "/var/lib/juju/agents/unit-kfp-api-0/charm/lib/char
```

it is clearly from DB

**Comment by ca-scribner** [comment]
I think during the discussion the thought was that the remove handler needs data from the DB, and that would be why a DB data fetch would block things.  But I don't see that in this traceback so it might have been something else
