### ISSUE TITLE
KFP API itests failed because MinIO had ImagePullBackOff yet the tests continued

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/kfp-operators#315]
Integration tests for a PR that updated a random text https://github.com/canonical/kfp-operators/pull/269 failed. So we have a race in the existing code https://github.com/canonical/kfp-operators/tree/38fd0f0d8ae5a6195930add44543700986bfc891.

Initially I see a lot of logs from juju, while waiting for the `kfp-viz` and `minio` Charms, with `ImagePullBackOff` errors, which I exposed in https://github.com/canonical/bundle-kubeflow/issues/655#issuecomment-1696987294

Then the pytest code took `1595.74 seconds`, which is 26 minutes, to complete. The most immediate logs I see are:

In the logs I see that all Charms ended up becoming active. Yet I see a ton of errors for failing to handle events for MinIO and KFP Viz, which took too long to get started with `ImagePullBackOff` errors.

The question here is: I see in the end the Charms became active, why didn't then the tests unblock and succeed?
```
------------------------------ live log teardown -------------------------------
INFO     pytest_operator.plugin:plugin.py:790 Model status:

Model            Controller                Cloud/Region        Version  SLA          Timestamp
test-charm-uld9  github-pr-f81f7-microk8s  microk8s/localhost  2.9.44   unsupported  19:58:28Z

App      Version                Status  Scale  Charm                    Channel         Rev  Address         Exposed  Message
kfp-api                         active      1  kfp-api                                    0  10.152.183.71   no       
kfp-db   mariadb/server:10.3    active      1  charmed-osm-mariadb-k8s  latest/stable    35  10.152.183.160  no       ready
kfp-viz  res:oci-image@3de6f3c  active      1  kfp-viz                  2.0/stable      476  10.152.183.137  no       
minio    res:oci-image@1755999  active      1  minio                    ckf-1.7/stable  186  10.152.183.133  no       

Unit        Workload  Agent  Address      Ports              Message
kfp-api/0*  active    idle   10.1.50.201                     
kfp-db/0*   active    idle   10.1.50.207  3306/TCP           ready
kfp-viz/0*  active    idle   10.1.50.208  8888/TCP           
minio/0*    active    idle   10.1.50.210  9000/TCP,9001/TCP  

```

<details><summary>Full logs</summary>

```
r: unknown container reason "ImagePullBackOff": Back-off pulling image "registry.jujucharms.com/charm/81j63o4a2ldarn1umc22iyjz1q9l9g0sx5b8j/oci-image@sha256:1755999849a392bdf00b778705f4cf5c1c971a1ef55a17e9075e56f8d58bdc2f"
INFO     juju.model:model.py:2618 Waiting for model:
  kfp-viz/0 [idle] active: 
  minio/0 [idle] error: unknown container reason "ImagePullBackOff": Back-off pulling image "registry.jujucharms.com/charm/81j63o4a2ldarn1umc22iyjz1q9l9g0sx5b8j/oci-image@sha256:1755999849a392bdf00b778705f4cf5c1c971a1ef55a17e9075e56f8d58bdc2f"
INFO     juju.model:model.py:2618 Waiting for model:
  minio/0 [idle] active: 
PASSED
tests/integration/test_charm.py::TestCharm::test_relational_db_relation_with_mysql_relation FAILED
tests/integration/test_charm.py::TestCharm::test_relational_db_relation_with_mysql_k8s XFAIL
tests/integration/test_charm.py::TestCharm::test_msql_relation_with_relational_db_relation XFAIL
tests/integration/test_charm.py::TestCharm::test_prometheus_grafana_integration XFAIL
tests/integration/test_charm.py::TestCharm::test_remove_application XFAIL
------------------------------ live log teardown -------------------------------
INFO     pytest_operator.plugin:plugin.py:790 Model status:

Model            Controller                Cloud/Region        Version  SLA          Timestamp
test-charm-uld9  github-pr-f81f7-microk8s  microk8s/localhost  2.9.44   unsupported  19:58:28Z

App      Version                Status  Scale  Charm                    Channel         Rev  Address         Exposed  Message
kfp-api                         active      1  kfp-api                                    0  10.152.183.71   no       
kfp-db   mariadb/server:10.3    active      1  charmed-osm-mariadb-k8s  latest/stable    35  10.152.183.160  no       ready
kfp-viz  res:oci-image@3de6f3c  active      1  kfp-viz                  2.0/stable      476  10.152.183.137  no       
minio    res:oci-image@1755999  active      1  minio                    ckf-1.7/stable  186  10.152.183.133  no       

Unit        Workload  Agent  Address      Ports              Message
kfp-api/0*  active    idle   10.1.50.201                     
kfp-db/0*   active    idle   10.1.50.207  3306/TCP           ready
kfp-viz/0*  active    idle   10.1.50.208  8888/TCP           
minio/0*    active    idle   10.1.50.210  9000/TCP,9001/TCP  



INFO     pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-kfp-api-0: 19:38:14 ERROR unit.kfp-api/0.juju-log Failed to handle <LeaderElectedEvent via KfpApiOperator/on/leader_elected[21]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:16 ERROR unit.kfp-api/0.juju-log Failed to handle <PebbleReadyEvent via KfpApiOperator/on/ml_pipeline_api_server_pebble_ready[26]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:18 ERROR unit.kfp-api/0.juju-log Failed to handle <ConfigChangedEvent via KfpApiOperator/on/config_changed[31]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:23 ERROR unit.kfp-api/0.juju-log mysql:0: Failed to handle <RelationJoinedEvent via KfpApiOperator/on/mysql_relation_joined[41]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:25 ERROR unit.kfp-api/0.juju-log mysql:0: Failed to handle <RelationChangedEvent via KfpApiOperator/on/mysql_relation_changed[46]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:43 ERROR unit.kfp-api/0.juju-log object-storage:1: Failed to handle <RelationChangedEvent via KfpApiOperator/on/object_storage_relation_changed[61]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:45 ERROR unit.kfp-api/0.juju-log kfp-viz:2: Failed to handle <RelationChangedEvent via KfpApiOperator/on/kfp_viz_relation_changed[66]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:49 ERROR unit.kfp-api/0.juju-log mysql:0: Failed to handle <RelationChangedEvent via KfpApiOperator/on/mysql_relation_changed[71]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:52 ERROR unit.kfp-api/0.juju-log kfp-viz:2: Failed to handle <RelationChangedEvent via KfpApiOperator/on/kfp_viz_relation_changed[76]> with error: List of <ops.model.Relation object-storage:1> versions not found for apps: minio
unit-kfp-api-0: 19:38:57 ERROR unit.kfp-api/0.juju-log object-storage:1: Failed to generate container configuration.
unit-kfp-api-0: 19:38:57 ERROR unit.kfp-api/0.juju-log object-storage:1: Failed to handle <RelationChangedEvent via KfpApiOperator/on/object_storage_relation_changed[81]> with error: Waiting for kfp-viz relation data
unit-kfp-api-0: 19:39:00 ERROR unit.kfp-api/0.juju-log kfp-viz:2: Failed to generate container configuration.
unit-kfp-api-0: 19:39:01 ERROR unit.kfp-api/0.juju-log kfp-viz:2: Failed to handle <RelationChangedEvent via KfpApiOperator/on/kfp_viz_relation_changed[86]> with error: Waiting for kfp-viz relation data

INFO     pytest_operator.plugin:plugin.py:812 juju-crashdump finished [0]
INFO     pytest_operator.plugin:plugin.py:884 Resetting model test-charm-uld9...
INFO     pytest_operator.plugin:plugin.py:873    Destroying applications kfp-api
INFO     pytest_operator.plugin:plugin.py:873    Destroying applications kfp-db
INFO     pytest_operator.plugin:plugin.py:873    Destroying applications minio
INFO     pytest_operator.plugin:plugin.py:873    Destroying applications kfp-viz
INFO     pytest_operator.plugin:plugin.py:889 Not waiting on reset to complete.
INFO     pytest_operator.plugin:plugin.py:862 Forgetting main...


=================================== FAILURES ===================================
__________ TestCharm.test_relational_db_relation_with_mysql_relation ___________
Traceback (most recent call last):
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 532, in inner
    _loop.run_until_complete(task)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/kfp-operators/kfp-operators/charms/kfp-api/tests/integration/test_charm.py", line 80, in test_relational_db_relation_with_mysql_relation
    await ops_test.model.deploy(
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/model.py", line [168](https://github.com/canonical/kfp-operators/actions/runs/5979649899/job/16224169467?pr=269#step:5:169)6, in deploy
    resources = await self._add_charmhub_resources(res.app_name,
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/model.py", line [181](https://github.com/canonical/kfp-operators/actions/runs/5979649899/job/16224169467?pr=269#step:5:182)9, in _add_charmhub_resources
    res = await charm_facade.CharmInfo(entity_url)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 502, in wrapper
    result = cls.from_json(reply['response'])
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 673, in from_json
    return cls(**d)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 4962, in __init__
    meta_ = CharmMeta.from_json(meta) if meta else None
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 673, in from_json
    return cls(**d)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 5474, in __init__
    assumes_expr_ = ExpressionTree.from_json(assumes_expr) if assumes_expr else None
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 687, in from_json
    cls.splitEntries(i, d)
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 713, in splitEntries
    result_dict[entry] = ''
TypeError: unhashable type: 'dict'
</details>

**Comment by NohaIhab** [comment]
We no longer run into this issue in the CI
