### ISSUE TITLE
Frontend ROCK fails to start in KFP deployment scenario

### ISSUE THREAD

**Issue by i-chvets** [canonical/kfp-operators#337]
### Bug Description

Frontend ROCK (https://github.com/canonical/pipelines-rocks/blob/main/frontend/rockcraft.yaml) fails to start when deployed as part of KFP UI charm.

When ROCK image is started manually process starts correctly:
```
$ docker run charmedkubeflow/frontend:2.0.0_22.04_1 exec pebble exec node /server/dist/server.js /client/ 3000
2023-09-26T17:48:07.062Z [pebble] Started daemon.
2023-09-26T17:48:07.077Z [pebble] POST /v1/exec 14.227315ms 202
2023-09-26T17:48:07.091Z [pebble] GET /v1/tasks/1/websocket/control 13.627817ms 200
2023-09-26T17:48:07.092Z [pebble] GET /v1/tasks/1/websocket/stdio 68.47µs 200
2023-09-26T17:48:07.092Z [pebble] GET /v1/tasks/1/websocket/stderr 62.481µs 200
2023-09-26T17:48:07.107Z [pebble] POST /v1/exec 12.340551ms 202
2023-09-26T17:48:07.119Z [pebble] GET /v1/tasks/2/websocket/control 12.146952ms 200
2023-09-26T17:48:07.120Z [pebble] GET /v1/tasks/2/websocket/stdio 49.477µs 200
2023-09-26T17:48:07.120Z [pebble] GET /v1/tasks/2/websocket/stderr 25.76µs 200
{
  argo: {
    archiveArtifactory: 'minio',
    archiveBucketName: 'mlpipeline',
    archiveLogs: false,
    archivePrefix: 'logs'
  },
  pod: { logContainerName: 'main' },
  artifacts: 'Artifacts config contains credentials, so it is omitted',
  metadata: { envoyService: { host: 'localhost', port: '9090' } },
  pipeline: { host: 'localhost', port: '3001' },
  server: {
    apiVersion1Prefix: 'apis/v1beta1',
    apiVersion2Prefix: 'apis/v2beta1',
    basePath: '/pipeline',
    deployment: 'NOT_SPECIFIED',
    hideSideNav: false,
    port: 3000,
    staticDir: '/client'
  },
  viewer: {
    tensorboard: {
      podTemplateSpec: undefined,
      tfImageName: 'tensorflow/tensorflow'
    }
  },
  visualizations: { allowCustomVisualizations: false },
  gkeMetadata: { disabled: false },
  auth: {
    enabled: false,
    kubeflowUserIdHeader: 'x-goog-authenticated-user-email',
    kubeflowUserIdPrefix: 'accounts.google.com:'
  }
}
[HPM] Proxy created: /  ->  http://localhost:9090
[HPM] Proxy created: /  ->  http://127.0.0.1
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /  ->  http://127.0.0.1
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /  ->  http://127.0.0.1
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /  ->  http://127.0.0.1
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /  ->  http://localhost:3001
[HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
[HPM] Proxy created: /  ->  http://localhost:3001
[HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
[HPM] Proxy created: /  ->  http://localhost:3001
[HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
[HPM] Proxy created: /  ->  http://localhost:3001
[HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
. . . 
Server listening at http://localhost:3000
```

Directory, which is given as an option, and `index.html` file are present in the container:
```
$ docker run charmedkubeflow/frontend:2.0.0_22.04_1 exec pebble ls /client
2023-09-26T18:57:50.283Z [pebble] Started daemon.
2023-09-26T18:57:50.322Z [pebble] POST /v1/exec 35.774146ms 202
2023-09-26T18:57:50.322Z [pebble] GET /v1/tasks/1/websocket/control 133.504µs 200
2023-09-26T18:57:50.323Z [pebble] GET /v1/tasks/1/websocket/stdio 104.908µs 200
2023-09-26T18:57:50.323Z [pebble] GET /v1/tasks/1/websocket/stderr 70.73µs 200
2023-09-26T18:57:50.327Z [pebble] GET /v1/files?action=list&path=%2Fclient 551.194µs 200
asset-manifest.json
index.html
static
2023-09-26T18:57:50.354Z [pebble] GET /v1/changes/1/wait 30.396299ms 200
```

However, when deployed by KFP UI charm it fails to find `/client/index.html` file, in directory which is supplied as part of service command. See *To Reproduce* section for more details.

### To Reproduce

1. Deploy `kfp-ui` charm with ROCK as workload image: `juju deploy kfp-ui kfp-ui-test --channel=1.7/stable --resource="oci-image=charmedkubeflow/frontend:2.0.0_22.04_1"`
2. Check logs: `microk8s.kubectl -n kubeflow logs kfp-ui-test-5fdd45477f-gtbcp`
3. Observe error in the logs:
  ```
  Error: ENOENT: no such file or directory, open '/client/index.html'
     at Object.openSync (fs.js:498:3)
     at Object.readFileSync (fs.js:394:35)
     at loadIndexHtml (/server/dist/handlers/index-html.js:36:22)
     at Object.getIndexHTMLHandler (/server/dist/handlers/index-html.js:22:41)
     at createUIServer (/server/dist/app.js:249:41)
     at new UIServer (/server/dist/app.js:51:20)
     at Object.<anonymous> (/server/dist/server.js:33:11)
     at Module._compile (internal/modules/cjs/loader.js:1114:14)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
     at Module.load (internal/modules/cjs/loader.js:979:32) {
   errno: -2,
   syscall: 'open',
   code: 'ENOENT',
   path: '/client/index.html'
```

See relavant logs for detailed log.

### Environment

The error describe in this issue can be observed in:
- Compete CKF deployment.

### Relevant log output

```shell
2023-09-26T18:23:10.958Z [pebble] Started daemon.
2023-09-26T18:23:10.973Z [pebble] POST /v1/services 7.380904ms 202
2023-09-26T18:23:10.974Z [pebble] Started default services with change 1.
2023-09-26T18:23:10.980Z [pebble] Service "ml-frontend" starting: node /server/dist/server.js /client/ 3000
2023-09-26T18:23:15.501Z [ml-frontend] {
2023-09-26T18:23:15.501Z [ml-frontend]   argo: {
2023-09-26T18:23:15.501Z [ml-frontend]     archiveArtifactory: 'minio',
2023-09-26T18:23:15.501Z [ml-frontend]     archiveBucketName: 'mlpipeline',
2023-09-26T18:23:15.501Z [ml-frontend]     archiveLogs: false,
2023-09-26T18:23:15.501Z [ml-frontend]     archivePrefix: 'logs'
2023-09-26T18:23:15.501Z [ml-frontend]   },
2023-09-26T18:23:15.501Z [ml-frontend]   pod: { logContainerName: 'main' },
2023-09-26T18:23:15.501Z [ml-frontend]   artifacts: 'Artifacts config contains credentials, so it is omitted',
2023-09-26T18:23:15.501Z [ml-frontend]   metadata: { envoyService: { host: 'localhost', port: '9090' } },
2023-09-26T18:23:15.501Z [ml-frontend]   pipeline: { host: 'kfp-api.kubeflow', port: '8888' },
2023-09-26T18:23:15.501Z [ml-frontend]   server: {
2023-09-26T18:23:15.501Z [ml-frontend]     apiVersion1Prefix: 'apis/v1beta1',
2023-09-26T18:23:15.501Z [ml-frontend]     apiVersion2Prefix: 'apis/v2beta1',
2023-09-26T18:23:15.501Z [ml-frontend]     basePath: '/pipeline',
2023-09-26T18:23:15.501Z [ml-frontend]     deployment: 'KUBEFLOW',
2023-09-26T18:23:15.501Z [ml-frontend]     hideSideNav: true,
2023-09-26T18:23:15.501Z [ml-frontend]     port: 3000,
2023-09-26T18:23:15.501Z [ml-frontend]     staticDir: '/client'
2023-09-26T18:23:15.501Z [ml-frontend]   },
2023-09-26T18:23:15.501Z [ml-frontend]   viewer: {
2023-09-26T18:23:15.501Z [ml-frontend]     tensorboard: { podTemplateSpec: [Object], tfImageName: 'tensorflow/tensorflow' }
2023-09-26T18:23:15.501Z [ml-frontend]   },
2023-09-26T18:23:15.501Z [ml-frontend]   visualizations: { allowCustomVisualizations: true },
2023-09-26T18:23:15.501Z [ml-frontend]   gkeMetadata: { disabled: false },
2023-09-26T18:23:15.501Z [ml-frontend]   auth: {
2023-09-26T18:23:15.501Z [ml-frontend]     enabled: true,
2023-09-26T18:23:15.501Z [ml-frontend]     kubeflowUserIdHeader: 'kubeflow-userid',
2023-09-26T18:23:15.501Z [ml-frontend]     kubeflowUserIdPrefix: ''
2023-09-26T18:23:15.501Z [ml-frontend]   }
2023-09-26T18:23:15.501Z [ml-frontend] }
2023-09-26T18:23:15.519Z [ml-frontend] [HPM] Proxy created: [Function (anonymous)]  ->  /artifacts
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Proxy created: /  ->  http://localhost:9090
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Proxy created: /  ->  http://127.0.0.1
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Proxy created: /  ->  http://127.0.0.1
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Proxy created: /  ->  http://127.0.0.1
2023-09-26T18:23:15.528Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Proxy created: /  ->  http://127.0.0.1
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Proxy created: /  ->  http://kfp-api.kubeflow:8888
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Proxy created: /  ->  http://kfp-api.kubeflow:8888
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Proxy created: /  ->  http://kfp-api.kubeflow:8888
2023-09-26T18:23:15.532Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
2023-09-26T18:23:15.533Z [ml-frontend] [HPM] Proxy created: /  ->  http://kfp-api.kubeflow:8888
2023-09-26T18:23:15.533Z [ml-frontend] [HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
2023-09-26T18:23:15.536Z [ml-frontend] internal/fs/utils.js:332
2023-09-26T18:23:15.536Z [ml-frontend]     throw err;
2023-09-26T18:23:15.536Z [ml-frontend]     ^
2023-09-26T18:23:15.536Z [ml-frontend] 
2023-09-26T18:23:15.536Z [ml-frontend] Error: ENOENT: no such file or directory, open '/client/index.html'
2023-09-26T18:23:15.536Z [ml-frontend]     at Object.openSync (fs.js:498:3)
2023-09-26T18:23:15.536Z [ml-frontend]     at Object.readFileSync (fs.js:394:35)
2023-09-26T18:23:15.536Z [ml-frontend]     at loadIndexHtml (/server/dist/handlers/index-html.js:36:22)
2023-09-26T18:23:15.536Z [ml-frontend]     at Object.getIndexHTMLHandler (/server/dist/handlers/index-html.js:22:41)
2023-09-26T18:23:15.536Z [ml-frontend]     at createUIServer (/server/dist/app.js:249:41)
2023-09-26T18:23:15.536Z [ml-frontend]     at new UIServer (/server/dist/app.js:51:20)
2023-09-26T18:23:15.536Z [ml-frontend]     at Object.<anonymous> (/server/dist/server.js:33:11)
2023-09-26T18:23:15.536Z [ml-frontend]     at Module._compile (internal/modules/cjs/loader.js:1114:14)
2023-09-26T18:23:15.536Z [ml-frontend]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
2023-09-26T18:23:15.536Z [ml-frontend]     at Module.load (internal/modules/cjs/loader.js:979:32) {
2023-09-26T18:23:15.536Z [ml-frontend]   errno: -2,
2023-09-26T18:23:15.536Z [ml-frontend]   syscall: 'open',
2023-09-26T18:23:15.536Z [ml-frontend]   code: 'ENOENT',
2023-09-26T18:23:15.536Z [ml-frontend]   path: '/client/index.html'
2023-09-26T18:23:15.536Z [ml-frontend] }
2023-09-26T18:23:15.546Z [pebble] Service "ml-frontend" stopped unexpectedly with code 1
2023-09-26T18:23:15.547Z [pebble] Service "ml-frontend" on-failure action is "restart", waiting ~500ms before restart (backoff 1)
```

### Additional context

N/A

**Comment by orfeas-k** [comment]
After re-building the frontend ROCK, I tried `docker run -ti frontend:2.0.3 exec bash` and then inside the image
```
_daemon_@254cceb58cd5:~$ pwd
/var/lib/pebble/default
_daemon_@254cceb58cd5:~$ ls /client
build
_daemon_@254cceb58cd5:~$ ls /client/build
asset-manifest.json  index.html  static
```
thus, it looks like the files aren't copied in `/client` directory. This can be fixed by:
```diff
-        cp -a build ${CRAFT_PART_INSTALL}/client
+        cp -a build/* ${CRAFT_PART_INSTALL}/client
```
