### ISSUE TITLE
kfp-ui fails reading json data from /etc/config/viewer-pod-template.json`

### ISSUE THREAD

**Issue by orfeas-k** [canonical/kfp-operators#603]
### Bug Description

During kfp-ui startup, kfp-ui fails to read data from '/etc/config/viewer-pod-template.json'. The charm seems to be [pushing an empty file](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-ui/src/templates/viewer-pod-template.json).

Comparing to an upstream KF deployment, this file has the following content
```json
{
    "spec": {
        "serviceAccountName": "default-editor"
    }
}
```
defined in the upstream [configmap (patch)](https://github.com/kubeflow/pipelines/blob/58ce09e07d031964905020c749e77bf0f37e83d4/manifests/kustomize/base/installs/multi-user/pipelines-ui/configmap-patch.yaml#L8-L14). This was observed on a CKF deployment that was using the upstream kfp images also. Thus, it could be that this file is present by default and the charm is overriding it with the empty one.

### To Reproduce

Deploy CKF 1.9

### Environment

Microk8s 1.29, juju 3.4.6

### Relevant Log Output

```shell
2024-11-14T14:57:49.233Z [ml-pipeline-ui] Failed reading json data from '/etc/config/viewer-pod-template.json':
2024-11-14T14:57:49.238Z [ml-pipeline-ui] SyntaxError: Unexpected end of JSON input
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at JSON.parse (<anonymous>)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Object.loadJSON (/server/dist/utils.js:143:21)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Object.loadConfigs (/server/dist/configs.js:237:42)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Object.<anonymous> (/server/dist/server.js:29:25)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Module.load (node:internal/modules/cjs/loader:1119:32)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Module._load (node:internal/modules/cjs/loader:960:12)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
2024-11-14T14:57:49.238Z [ml-pipeline-ui]     at node:internal/main/run_main_module:23:47
```

**Comment by NohaIhab** [comment]
We can address this while working on #869
